### ISSUE TITLE
 Object does not exist at path “/org/freedesktop/UPower/devices/battery_BAT0”

### ISSUE THREAD

**Issue by veneficium42** [mrHeavenli/akkufetch#3]
Distro: Arch
DE: Gnome
WM: Wayland

```
Traceback (most recent call last):
  File "/usr/bin/akkufetch", line 27, in <module>
    config.generate_dynamic(battery["Percentage"])
                            ~~~~~~~^^^^^^^^^^^^^^
  File "/usr/share/akkufetch/src/dbus_handler.py", line 14, in __getitem__
    value = self.interface.Get("org.freedesktop.UPower.Device", item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/UPower/devices/battery_BAT0”

**Comment by mrHeavenli** [comment]
Hello,
This error is likely because the default battery path is not valid on your machine.
If you run ` upower --enumerate ` , you will get something like this:
```
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/line_power_ucsi_source_psy_USBC000o001
/org/freedesktop/UPower/devices/DisplayDevice
```
If you're on a laptop, this should contain the path of your battery.
Edit the configuration file and replace the value of `battery_path` with whatever path it is on your machine.

**Comment by veneficium42** [comment]
Thanks! Maybe this should be added to the readme!
